package com.heathen.ialemus.ui.theme

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.graphics.Color
import com.heathen.ialemus.core.model.ThemeGroup
import com.heathen.ialemus.core.model.ThemeId

data class IalemusThemeTokens(
    val glowColor: Color,
    val warningColor: Color,
    val scanlineColor: Color,
    val terminalGridColor: Color,
    val waveformColor: Color,
    val dangerAccent: Color,
    val successAccent: Color,
    val hudBorderColor: Color,
    val panelOverlay: Color,
    val surfaceDeep: Color,
    val textPrimary: Color,
    val textMuted: Color,
    val accentActive: Color,
    val navActive: Color,
    val showGrid: Boolean = true,
    val showScanlines: Boolean = true,
    val useHexAccents: Boolean = false,
)

val LocalIalemusTokens = compositionLocalOf { eva01Tokens() }

fun tokensFor(themeId: ThemeId, dapMode: Boolean = false): IalemusThemeTokens {
    val base = when (themeId) {
        ThemeId.EVA_01_BERSERK -> eva01Tokens()
        ThemeId.EVA_00_PROTOTYPE -> evaTokens(
            glow = Eva00Primary,
            warning = Eva00Primary,
            scanline = Color(0x1AFFC107),
            grid = Color(0x22FFC107),
            waveform = Eva00Secondary,
            danger = Color(0xFFFF5252),
            success = Eva00Primary,
            border = Eva00Primary.copy(alpha = 0.5f),
            panel = Eva00Elevated,
            deep = Eva00Background,
            text = Eva00OnBackground,
            accent = Eva00Primary,
            nav = Eva00Primary,
            hex = true,
        )
        ThemeId.EVA_02_ASUKA_RED -> evaTokens(
            glow = Eva02Primary,
            warning = Eva02Secondary,
            scanline = Color(0x1AE53935),
            grid = Color(0x22E53935),
            waveform = Eva02Secondary,
            danger = Eva02Primary,
            success = Color(0xFFFFAB40),
            border = Eva02Primary.copy(alpha = 0.55f),
            panel = Eva02Elevated,
            deep = Eva02Background,
            text = Eva02OnBackground,
            accent = Eva02Secondary,
            nav = Eva02Primary,
            hex = true,
        )
        ThemeId.EVA_03_SHADOW -> evaTokens(
            glow = Eva03Secondary,
            warning = Eva03Primary,
            scanline = Color(0x1A5C6BC0),
            grid = Color(0x227E57C2),
            waveform = Eva03Primary,
            danger = Color(0xFFFF5252),
            success = Eva03Primary,
            border = Eva03Secondary.copy(alpha = 0.5f),
            panel = Eva03Elevated,
            deep = Eva03Background,
            text = Eva03OnBackground,
            accent = Eva03Secondary,
            nav = Eva03Primary,
            hex = true,
        )
        ThemeId.EVA_05_MASS_PRODUCTION -> evaTokens(
            glow = Eva05Primary,
            warning = Eva05Tertiary,
            scanline = Color(0x14FFFFFF),
            grid = Color(0x22BDBDBD),
            waveform = Eva05Secondary,
            danger = Eva05Tertiary,
            success = Eva05Primary,
            border = Eva05Secondary.copy(alpha = 0.45f),
            panel = Eva05Elevated,
            deep = Eva05Background,
            text = Eva05OnBackground,
            accent = Eva05Primary,
            nav = Eva05Tertiary,
            hex = true,
        )
        ThemeId.TERMINAL_DOGMA -> evaTokens(
            glow = DogmaPrimary,
            warning = DogmaSecondary,
            scanline = Color(0x1AFF1744),
            grid = Color(0x22FF1744),
            waveform = DogmaSecondary,
            danger = DogmaPrimary,
            success = DogmaSecondary,
            border = DogmaPrimary.copy(alpha = 0.6f),
            panel = DogmaElevated,
            deep = DogmaBackground,
            text = DogmaOnBackground,
            accent = DogmaSecondary,
            nav = DogmaPrimary,
            hex = true,
        )
        ThemeId.TACTICAL_COMMAND -> evaTokens(
            glow = TacticalPrimary,
            warning = TacticalSecondary,
            scanline = Color(0x1AFF5722),
            grid = Color(0x22FF5722),
            waveform = TacticalPrimary,
            danger = Color(0xFFD50000),
            success = Color(0xFFFFAB00),
            border = TacticalPrimary.copy(alpha = 0.55f),
            panel = TacticalElevated,
            deep = TacticalBackground,
            text = TacticalOnBackground,
            accent = TacticalSecondary,
            nav = TacticalPrimary,
            hex = true,
        )
        ThemeId.GHOST_IN_THE_CODE -> ialemusTokens(
            glow = GhostPrimary,
            warning = GhostWarning,
            scanline = Color(0x189BF6FF),
            grid = Color(0x1A7DE2D1),
            waveform = GhostSecondary,
            danger = GhostError,
            success = GhostSecondary,
            border = GhostPrimary.copy(alpha = 0.42f),
            panel = GhostElevated,
            deep = GhostBackground,
            text = GhostOnBackground,
            accent = GhostPrimary,
            nav = GhostSecondary,
        )
        ThemeId.TERMINAL_KITTIE -> ialemusTokens(
            glow = KittiePrimary,
            warning = KittieWarning,
            scanline = Color(0x18FF7AD9),
            grid = Color(0x1A72FF9F),
            waveform = KittieSecondary,
            danger = KittieError,
            success = KittieSecondary,
            border = KittiePrimary.copy(alpha = 0.45f),
            panel = KittieElevated,
            deep = KittieBackground,
            text = KittieOnBackground,
            accent = KittiePrimary,
            nav = KittieSecondary,
        )
        ThemeId.CHTHONIC_SIGNAL -> ialemusTokens(
            glow = ChthonicPrimary,
            warning = ChthonicWarning,
            scanline = Color(0x18FF5A1F),
            grid = Color(0x1A3CFF88),
            waveform = ChthonicSecondary,
            danger = ChthonicError,
            success = ChthonicSecondary,
            border = ChthonicPrimary.copy(alpha = 0.5f),
            panel = ChthonicElevated,
            deep = ChthonicBackground,
            text = ChthonicOnBackground,
            accent = ChthonicPrimary,
            nav = ChthonicSecondary,
        )
        ThemeId.NEON_OSSUARY -> ialemusTokens(
            glow = OssuarySecondary,
            warning = OssuaryWarning,
            scanline = Color(0x14E8E1D9),
            grid = Color(0x1AB45CFF),
            waveform = OssuaryTertiary,
            danger = OssuaryError,
            success = OssuaryTertiary,
            border = OssuarySecondary.copy(alpha = 0.45f),
            panel = OssuaryElevated,
            deep = OssuaryBackground,
            text = OssuaryOnBackground,
            accent = OssuarySecondary,
            nav = OssuaryPrimary,
        )
        ThemeId.ARCHIVE_BLACK -> ialemusTokens(
            glow = ArchiveBlackPrimary,
            warning = ArchiveBlackWarning,
            scanline = Color(0x08FFFFFF),
            grid = Color(0x0C8A8A8A),
            waveform = ArchiveBlackSecondary,
            danger = ArchiveBlackError,
            success = ArchiveBlackSuccess,
            border = ArchiveBlackSecondary.copy(alpha = 0.35f),
            panel = ArchiveBlackElevated,
            deep = ArchiveBlackBackground,
            text = ArchiveBlackOnBackground,
            accent = ArchiveBlackPrimary,
            nav = ArchiveBlackTertiary,
            gridOn = false,
            scanOn = false,
        )
        ThemeId.FALLOUT_CRT -> ialemusTokens(
            glow = FalloutPrimary,
            warning = FalloutWarning,
            scanline = Color(0x227CFF6B),
            grid = Color(0x1A7CFF6B),
            waveform = FalloutSecondary,
            danger = FalloutError,
            success = FalloutPrimary,
            border = FalloutPrimary.copy(alpha = 0.4f),
            panel = FalloutElevated,
            deep = FalloutBackground,
            text = FalloutOnBackground,
            accent = FalloutPrimary,
            nav = FalloutTertiary,
        )
        ThemeId.CYBER_SHRINE -> ialemusTokens(
            glow = ShrinePrimary,
            warning = ShrineWarning,
            scanline = Color(0x18FF4FD8),
            grid = Color(0x1A3DDCFF),
            waveform = ShrineSecondary,
            danger = ShrineError,
            success = ShrineSecondary,
            border = ShrinePrimary.copy(alpha = 0.48f),
            panel = ShrineElevated,
            deep = ShrineBackground,
            text = ShrineOnBackground,
            accent = ShrinePrimary,
            nav = ShrineSecondary,
            hex = true,
        )
        ThemeId.CANDY_MALWARE -> ialemusTokens(
            glow = CandyPrimary,
            warning = CandyWarning,
            scanline = Color(0x18FF5EC4),
            grid = Color(0x1A00F5D4),
            waveform = CandySecondary,
            danger = CandyError,
            success = CandySuccess,
            border = CandyPrimary.copy(alpha = 0.45f),
            panel = CandyElevated,
            deep = CandyBackground,
            text = CandyOnBackground,
            accent = CandyPrimary,
            nav = CandySecondary,
        )
    }
    return if (dapMode) {
        base.copy(showGrid = false, showScanlines = false)
    } else {
        base
    }
}

private fun eva01Tokens() = IalemusThemeTokens(
    glowColor = Eva01Primary,
    warningColor = Eva01Tertiary,
    scanlineColor = Color(0x1A39FF14),
    terminalGridColor = Color(0x2239FF14),
    waveformColor = Eva01Secondary,
    dangerAccent = Eva01Error,
    successAccent = Eva01Secondary,
    hudBorderColor = Eva01Primary.copy(alpha = 0.55f),
    panelOverlay = Eva01Elevated.copy(alpha = 0.94f),
    surfaceDeep = Eva01Background,
    textPrimary = Eva01OnBackground,
    textMuted = Eva01OnBackground.copy(alpha = 0.68f),
    accentActive = Eva01Secondary,
    navActive = Eva01Secondary,
    useHexAccents = true,
)

private fun evaTokens(
    glow: Color,
    warning: Color,
    scanline: Color,
    grid: Color,
    waveform: Color,
    danger: Color,
    success: Color,
    border: Color,
    panel: Color,
    deep: Color,
    text: Color,
    accent: Color,
    nav: Color,
    hex: Boolean = true,
) = IalemusThemeTokens(
    glowColor = glow,
    warningColor = warning,
    scanlineColor = scanline,
    terminalGridColor = grid,
    waveformColor = waveform,
    dangerAccent = danger,
    successAccent = success,
    hudBorderColor = border,
    panelOverlay = panel,
    surfaceDeep = deep,
    textPrimary = text,
    textMuted = text.copy(alpha = 0.65f),
    accentActive = accent,
    navActive = nav,
    useHexAccents = hex,
)

private fun ialemusTokens(
    glow: Color,
    warning: Color,
    scanline: Color,
    grid: Color,
    waveform: Color,
    danger: Color,
    success: Color,
    border: Color,
    panel: Color,
    deep: Color,
    text: Color,
    accent: Color,
    nav: Color,
    gridOn: Boolean = true,
    scanOn: Boolean = true,
    hex: Boolean = false,
) = IalemusThemeTokens(
    glowColor = glow,
    warningColor = warning,
    scanlineColor = scanline,
    terminalGridColor = grid,
    waveformColor = waveform,
    dangerAccent = danger,
    successAccent = success,
    hudBorderColor = border,
    panelOverlay = panel,
    surfaceDeep = deep,
    textPrimary = text,
    textMuted = text.copy(alpha = 0.62f),
    accentActive = accent,
    navActive = nav,
    showGrid = gridOn,
    showScanlines = scanOn,
    useHexAccents = hex,
)

/** Whether hex HUD accents should appear for the active theme (EVA + Cyber Shrine). */
fun themeUsesHexAccents(themeId: ThemeId): Boolean =
    themeId.group == ThemeGroup.EVA || themeId == ThemeId.CYBER_SHRINE
